Document: os-loader-gui
Title: Debian os-loader-gui Manual
Author: <insert document author here>
Abstract: This manual describes what os-loader-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/os-loader-gui/os-loader-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/os-loader-gui/os-loader-gui.ps.gz

Format: text
Files: /usr/share/doc/os-loader-gui/os-loader-gui.text.gz

Format: HTML
Index: /usr/share/doc/os-loader-gui/html/index.html
Files: /usr/share/doc/os-loader-gui/html/*.html
